# Generated by Django 4.0.6 on 2022-08-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportapplication',
            name='client_class',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Remote ID Display Provider'), (2, 'Registry Reader'), (3, 'Login only'), (4, 'Flight Spotlight Read - Write'), (5, 'Remote ID Service Provider'), (6, 'Flight Blender Read - Write'), (7, 'Aerobridge Read and Write'), (8, 'Permission Signing Client')], default=0),
        ),
    ]
