# Generated by Django 5.0.1 on 2024-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0003_passportapplication_post_logout_redirect_uris_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportapplication',
            name='client_class',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Login only'), (2, 'Client Credentials')], default=0),
        ),
    ]
