# Generated by Django 3.0.8 on 2020-07-30 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0004_auto_20200728_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportScope',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='audience',
            field=models.ManyToManyField(blank=True, related_name='application_audience', to='authprofiles.PassportAPI'),
        ),
        migrations.AddField(
            model_name='passportapi',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='api_scope', to='authprofiles.PassportScope'),
        ),
    ]
