# Generated by Django 3.0.8 on 2020-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0005_auto_20200730_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportapplication',
            name='client_class',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Remote ID Display Provider'), (2, 'Registry Reader'), (3, 'Login only'), (4, 'Flight Spotlight Reader'), (5, 'Flight Spotlight Service'), (6, 'Remote ID Service Provider')], default=0),
        ),
    ]
