# Generated by Django 3.1 on 2020-08-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0006_auto_20200731_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportapi',
            name='identifier',
            field=models.CharField(help_text='e.g. che.openskies.sh', max_length=140),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='client_class',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Remote ID Display Provider'), (2, 'Registry Reader'), (3, 'Login only'), (4, 'Flight Spotlight Reader'), (5, 'Flight Spotlight Writer'), (6, 'Remote ID Service Provider')], default=0),
        ),
        migrations.AlterField(
            model_name='passportscope',
            name='name',
            field=models.CharField(help_text='e.g. dss.read.identification_service_areas', max_length=140),
        ),
    ]
