# Generated by Django 3.1 on 2020-08-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0007_auto_20200810_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
