# Generated by Django 3.1.7 on 2021-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportapplication',
            name='client_class',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Remote ID Display Provider'), (2, 'Registry Reader'), (3, 'Login only'), (4, 'Flight Spotlight Reader'), (5, 'Flight Spotlight Writer'), (6, 'Remote ID Service Provider'), (7, 'Flight Blender Read - Write'), (8, 'Aerobridge Read and Write')], default=0),
        ),
    ]
