# Generated by Django 3.2.8 on 2021-11-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0010_auto_20210531_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportapplication',
            name='client_class',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Remote ID Display Provider'), (2, 'Registry Reader'), (3, 'Login only'), (4, 'Flight Spotlight Reader'), (5, 'Flight Spotlight Writer'), (6, 'Remote ID Service Provider'), (7, 'Flight Blender Read - Write'), (8, 'Aerobridge Read and Write'), (9, 'Sign JSON')], default=0),
        ),
    ]
